### ISSUE TITLE
Fix the logging for modules

### ISSUE THREAD

**Issue by lunarplasma** [lunarplasma/EDMC-CombatTracker#3]
@jberanek reports that the logger for the Data module (and the Display module?) is causing exceptions:

```
I mean the "Data" subdir in the plugin, where massacres.py lives.
```

_Originally posted by @jberanek in https://github.com/lunarplasma/EDMC-CombatTracker/issues/1#issuecomment-780581175_

**Comment by jberanek** [comment]
Display doesn't initialise a logger yet, so doesn't suffer the issue.

**Comment by lunarplasma** [comment]
@jberanek fix:

> Sorry, it was only spamming the log as the logging statement in the exception handling caused an exception itself, as logging in massacres.py was broken, because of it being in a subdir, fixed with:
> 
> ```
> plugin_name = os.path.basename(os.path.normpath(os.path.join(os.path.dirname(__file__), '..')))
> logger = logging.getLogger(f"{appname}.{plugin_name}")
> ```

**Comment by lunarplasma** [comment]
Fixed this by commonising the source location of `plugin_name`.
